---
- name: Install nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx
  become: true
