- hosts: webservers
  become: yes
  tasks:
    - name: Ensure python3-apt is installed
      raw: sudo apt-get update && sudo apt-get install -y python3-apt

    - name: Install nginx
      apt:
        name: nginx
        state: present
