- name: Install nginx
  hosts: webservers
  become: true
  vars:
    http_port: 8080
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Update nginx config
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
