- name: Setup webserver
  hosts: webservers
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      tags: install

    - name: Deploy config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      tags: config
