- name: Setup a simple web server
  hosts: webservers
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Update nginx default configuration
      shell: |
        sudo tee /etc/nginx/conf.d/default.conf > /dev/null <<'EOF'
        server {
            listen 80 default_server;
            listen [::]:80 default_server;

            server_name _;

            root /var/www/html;
            index index.html;

            location / {
                try_files $uri $uri/ =404;
            }
        }
        EOF

    - name: Copy homepage
      copy:
        content: "<h1>Hello from Ansible!</h1>"
        dest: /var/www/html/index.html

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
